// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/gopherdir/ui.go

// Package mock_gopherdir is a generated GoMock package.
package mock_gopherdir

import (
	gomock "github.com/golang/mock/gomock"
)

// MockUIRenderer is a mock of UIRenderer interface
type MockUIRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockUIRendererMockRecorder
}

// MockUIRendererMockRecorder is the mock recorder for MockUIRenderer
type MockUIRendererMockRecorder struct {
	mock *MockUIRenderer
}

// NewMockUIRenderer creates a new mock instance
func NewMockUIRenderer(ctrl *gomock.Controller) *MockUIRenderer {
	mock := &MockUIRenderer{ctrl: ctrl}
	mock.recorder = &MockUIRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUIRenderer) EXPECT() *MockUIRendererMockRecorder {
	return m.recorder
}
